### ISSUE TITLE
CUDA/cuDNN versions / shared with host nodes?

### ISSUE THREAD

**Issue by denclade** [Langhalsdino/Kubernetes-GPU-Guide#4]
First of all, thanks for your work, it's pretty easy to get everything up and running. I've just a question regarding CUDA versions ..

Usually Docker Images contain CUDA (e.g. in /usr/local/cuda-n.n/lib64) and set this location in the LD_LIBRARY_PATH. Here (or in general with kubernetes?) they need to be located in a shared folder with the host, so they need to share the hosts CUDA and cuDNN version.

With the scripts and samples from this repository I didn't get the GPU to work in the tf-jupyter container. I checked the LD_LIBRARY_PATH inside the container and it was set to: /usr/local/nvidia/lib:/usr/local/nvidia/lib64:

So I had to to the following to get it up and running:
sudo cp /usr/lib/x86_64-linux-gnu/libcuda* /usr/lib/nvidia-375/

But this comes with the issue, that the container uses the CUDA Version of the host node and so I would not be able to run containers with different CUDA versions on the same node, is this correct?

I have a few more questions about this..

Where gets the LD_LIBRARY_PATH variable of the container set to /usr/local/nvidia/lib:/usr/local/nvidia/lib64:? In the docker images (e.g. in the tensorflow/tensorflow used in the example .yaml you provided, it's set to the /usr/local/cuda... path)
I actually tried to set the LD_LIBRARY_PATH manually inside a running container to /usr/local/cuda../lib64 and it seems to work, is there an issue with this?

Or in general .. what's the correct way to get docker containers with different CUDA/CUDNN versions up and running with the Kubernetes GPU setup?

**Comment by Langhalsdino** [comment]
Hi Nobovbo,

thank you very much for your feedback and please excuse my late reply!
Since I am currently very busy preparing for exams and meeting other deadline, i may not be as fast as I want to.

The recommended Way:
Only use the same driver, Cuda, CudNN version across one machine and label it with a label corresponding to your setup. Then you can configure each job/deployment to require a certain label. (More info: [https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/) )

If you really want to run multiple versions across one machine try this:
Kubernetes currently only supports the same driver across one machine. Since CUDA is **mostly** backwards compatible you can install different versions on one machine.

Install each version in a different location (e.g. /usr/local/cuda-$V, /usr/local/cuda-$V/cuda)
Specify in each deployment, which version ($V) to use as follows:
```
spec:
      volumes:
      - hostPath:
          path: /usr/local/cuda-$V
        name: cuda
volumeMounts:
       - mountPath: /usr/local/nvidia/lib
           name: cuda
```
(This snipped might contain mistakes, since i can not test it right now, sorry :( )

Furthermore, thank you for the issue with my deployment, i will adjust it in the next weeks.
I hope this might be helpful. I will update this Guide after i have written my exams.

**Comment by Langhalsdino** [comment]
I tried to fix the deployment with some feedback from @noboevbo and Adhita 👍 . 

This is not tested, but should work :
[Gist of a updated deployment](https://gist.github.com/Langhalsdino/d848830f67f206eda86a72e3cb840e22)

**Comment by denclade** [comment]
Thanks for the updated deployment. I ended up with the solution you proposed - using different versions of cuda / cudnn on different machines and labels according to the versions. This works fine now. Nevertheless I hope for some Kubernetes updates with better GPU / CUDA support.
